### ISSUE TITLE
Camera loads a static image

### ISSUE THREAD

**Issue by krel99** [antoniocasino/movenet-space-invaders#1] opened 2024-01-04 10:44 UTC
I tried to install this game. The camera would only take a snapshot.

Console Error: Uncaught (in promise) OverconstrainedError in movenet-space-invade…n.up.railway.app/:1

**Comment by antoniocasino** [comment] 2024-01-07 06:44
What OS and browser are you using?
I currently tested it on Windows OS , with Chrome 120 and Edge 120 
Make sure to  enable the camera in the browser.
OverconstrainedError seems like an error related to the camera

**Comment by krel99** [comment] 2024-01-07 08:21
Linux (PopOS) with Brave. 
I tried again and instead of giving it permission till I close the site I gave it 24h and it appears to work. Interesting.

**Comment by antoniocasino** [comment] 2024-01-07 10:18
As far as I understood the issue is related to your camera browser config.
I will close the issue

**Closed as completed by antoniocasino** 2024-01-07 10:18 UTC
